package beadando;

import java.io.IOException;
import java.util.logging.Level;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 * Főmenü osztály a Sudokuhoz.
 *
 * @author Boruzs Tibor
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Konstruktor a főmenü osztályozásához, mely a főablak komponenseit
     * inicializálja.
     */
    public NewJFrame() {
        setAutoRequestFocus(true);
        initComponents();
    }
    /**
     * Naplózási objektum deklarálása, és inicializálása.
     */

    protected static Logger logger = LoggerFactory.getLogger(NewJFrame.class);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku for Prog.Körny. Main menu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        // setResizable(false);

        jButton1.setText("Új játék");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParserConfigurationException ex) {
                    java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SAXException ex) {
                    java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });

        jButton3.setText("Névjegy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Sudoku for Prog.Körny.");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Release Preview");

        jButton4.setText("Súgó");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton4ActionPerformed(evt);
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(95, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton3)
                                .addComponent(jButton4))
                        .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * A program névjegyének megtekintése.
     *
     * @param evt Az eseményt kiváltó kattintás.
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AboutAblak nevjegy = new AboutAblak(this, rootPaneCheckingEnabled);
        nevjegy.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Új játék indításának eseménykezelője.
     * @param evt Maga az egérkattintási esemény.
     * @throws IOException Input output kiével.
     * @throws ParserConfigurationException Parser kivétel.
     * @throws SAXException SAX feldolgozó kivétel az XML feldolgozáshoz.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException, ParserConfigurationException, SAXException {//GEN-FIRST:event_jButton1ActionPerformed

        int jatekszam;
        jatekszam = (int) (1 + Math.random() * 5220);
        //   String message = "A játékmenet száma: " + jatekszam + "\n" + "Under construction...";

        CreateGame cr = null;

        cr = new CreateGame();

        String message = null;
        message = cr.Gamecreator(jatekszam);
        int[] jatek = new int[83];
        for (int i = 7; i < 88; i++) {
            jatek[i - 6] = (int) message.charAt(i) - 48;
        }
        SudokuTable tábla = new SudokuTable(jatek);
        tábla.elokeszit(jatek, jatekszam);
        tábla.kopiz(jatek);
        tábla.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * A súgó gomb megnyomására megnyílik a rendszer alapértelmezett
     * böngészőjében a wikipédia oldala, benne a Sudokuról a fontosabb
     * információk.
     *
     * @param evt Az eseményt kiváltó egérkattintás.
     * @throws IOException Elérési kivétel, hiba.
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_jButton4ActionPerformed
        String URL = "http://hu.wikipedia.org/wiki/Sudoku";

        java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        logger.info("Sudoku for ProgKorny is loading...");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                logger.info("Sudoku for ProgKorny is started.");
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     *
     */
    private javax.swing.JButton jButton1;
    /**
     *
     */
    private javax.swing.JButton jButton3;
    /**
     *
     */
    private javax.swing.JButton jButton4;
    /**
     *
     */
    private javax.swing.JLabel jLabel1;
    /**
     *
     */
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
